### ISSUE TITLE
Config regex values - error's on startup.

### ISSUE THREAD

**Issue by andrewkm** [mfnalex/ChestSort#188]
ChestSort compiled against https://github.com/mfnalex/ChestSort/commit/02f4d96ff655814a5ce9e49cdaa52f42d8dded76
Paper 1.20.4 Build 496

The regex's in the default config seem to be causing errors on startup, and there's no way to disable them.
Even if I set that config's section to [] it still throws these errors:
https://pastebin.com/NkE6XJ39

**Comment by mfnalex** [comment]
Hi, the error are the quotes around the "interactivechat" inventory holder line.

Setting it to an empty list did not work in versions prior to 14.0.3 because of how Spigot falls back to default values for "null/empty" lists.

Possible fixes:
1. Add at least one entry to the blocked-inventory-holders-regex, or
2. Update to 14.0.3 (You'll still have to remove the interactive chat regex line from your old config if it still exists there).
